[[redirects]]
    from = "http://princebazawule.com/"
    to = "https://princebazawule.com/"
    status = 301
    force = true

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = '''
        max-age=63072000;
        includeSubDomains;
        preload'''
        